spring:
  application:
    name: charger-network-manager
  port:
    8103

eureka:
  client:
    region:  default
    registerWithEureka: true # if this is set to false, this service will not be registered with Eureka; won't be visible in the Eureka UI Monitor; assume won't be discoverable by other services
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://charger-network-discovery:8761/eureka/
